FROM node:17-alpine

ARG LOCAL_USER_ID=9001
ARG LOCAL_GROUP_ID=101

ENV USER orchestrator
ENV GROUP purpleteam
RUN echo user is: ${USER}, LOCAL_USER_ID is: ${LOCAL_USER_ID}, group is: ${GROUP}, LOCAL_GROUP_ID is: ${LOCAL_GROUP_ID}

RUN apk add --no-cache zip

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN apk add --no-cache shadow && \
    if [ -z "`getent group $LOCAL_GROUP_ID`" ]; then \
      addgroup -S -g $LOCAL_GROUP_ID $GROUP; \
    else \
      groupmod -n $GROUP `getent group $LOCAL_GROUP_ID | cut -d: -f1`; \
    fi && \
    if [ -z "`getent passwd $LOCAL_USER_ID`" ]; then \
      adduser -S -u $LOCAL_USER_ID -G $GROUP -s /bin/sh $USER; \
    else \
      usermod -l $USER -g $LOCAL_GROUP_ID -d /home/$USER -m `getent passwd $LOCAL_USER_ID | cut -d: -f1`; \
    fi

RUN mkdir -p /usr/src/app/ && chown $USER:$GROUP --recursive /usr/src/app/

WORKDIR /usr/src/app/

COPY package*.json /usr/src/app/

RUN npm install

COPY --chown=orchestrator:purpleteam . /usr/src/app/

USER $USER

EXPOSE 2000

CMD ["npm", "start"]