# Copyright (C) 2017-2022 BinaryMist Limited. All rights reserved.

# Use of this software is governed by the Business Source License
# included in the file /licenses/bsl.md

# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

version: "3.7"

networks:
  pt-net:
    ipam:
      config:
       - subnet: 172.25.0.0/24

services:
  orchestrator:
    ports:
      - "2000:2000"
    # Use type host until we can test link
    networks:
      pt-net:
        ipv4_address: 172.25.0.10
    build:
      context: ../
      # Build-time args
      args:
        LOCAL_USER_ID: ${LOCAL_USER_ID}
        LOCAL_GROUP_ID: ${LOCAL_GROUP_ID}
    environment:
      - NODE_ENV=local
    # Following values are analogous to their Dockerfile counterparts:
    # -i : Keep STDIN open even if not attached
    # -t : Allocate a pseudo-tty
    stdin_open: true
    tty: true
    container_name: pt-orchestrator-cont
    volumes:
      - type: bind
        source: ${HOST_DIR}
        target: /var/log/purpleteam/outcomes

