# https://docs.docker.com/compose/extends/

version: "3.7"

services:

  app-scanner:
    build:
      context: ../../purpleteam-app-scanner/
      # Build-time args.
      # These values are used in our IaC for AWS, specifically userData.tpl for the ECS hosts, as the host and container GID needs to match.
      args:
        LOCAL_USER_ID: 1031
        LOCAL_GROUP_ID: 1020

  orchestrator:
    build:
      context: ../
      # Build-time args.
      # These values are used in our IaC for AWS, specifically userData.tpl for the ECS hosts, as the host and container GID needs to match.
      args:
        LOCAL_USER_ID: 1030
        LOCAL_GROUP_ID: 1020
